import { Hono } from 'hono';
import ping from './routes/ping';
import weather from './routes/weather';
import issLocation from './routes/iss-location';
import wikipedia from './routes/wikipedia';
import silver from './routes/silver';
import oil from './routes/oil';
import gold from './routes/gold';
import platinum from './routes/platinum';
import copper from './routes/copper';
import gas from './routes/gas';
import stock from './routes/stock';
import indices from './routes/indices';
import fx from './routes/fx';
import crypto from './routes/crypto';
import regret from './routes/regret';
import minecraft from './routes/minecraft';
import status from './routes/status';
import hackatime from './routes/hackatime';
import crates from './routes/crates';
import keys from './routes/keys';
import authenticated from './routes/authenticated';
import apilist from './routes/apis';
import hcai from './routes/hcai';
import airline from './routes/airline';
import flights from './routes/flights';
import airport from './routes/airports';
import aircraft from './routes/aircraft';

const api = new Hono();

api.route('/ping', ping);
api.route('/weather', weather)
api.route('/iss-location', issLocation);
api.route('/wikipedia', wikipedia);
api.route('/silver', silver);
api.route('/oil', oil);
api.route('/gold', gold);
api.route('/platinum', platinum);
api.route('/copper', copper);
api.route('/gas', gas);
api.route('/stock', stock);
api.route('/index', indices);
api.route('/fx', fx);
api.route('/crypto', crypto);
api.route('/regret', regret);
api.route('/minecraft', minecraft);
api.route('/status', status);
api.route('/hackatime', hackatime);
api.route('/crates', crates);
api.route('/keys', keys);
api.route('/authenticated', authenticated);
api.route('/apis', apilist);
api.route('/hcai', hcai);
api.route('/airlines', airline);
api.route('/flights', flights);
api.route('/airports', airport);
api.route('/aircraft', aircraft);

export default api;
